In [2]:
import numpy as np 
import pandas as pd
import torch
import matplotlib.pyplot as plt

from torch import nn
from torch import optim
import torch.nn.functional as F

In [3]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()  # call __init__ method of the nn.module
        
        # fully connected layer 
        self.fc1 = nn.Linear(10,5)
        self.fc2 = nn.Linear(5,7)
        self.fc3 = nn.Linear(7,2)
        
    def forward(self, x):
        
        x= self.fc1(x)
        x=F.relu(x)
        x = self.fc2(x)
        x= F.relue(x)
        x = self.fc3(x)
        x = softmax(x,dim=1) # takes dim of the output size
        
        return x

model = Network()
model
    
        

Network(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=7, bias=True)
  (fc3): Linear(in_features=7, out_features=2, bias=True)
)

In [4]:
print(model.fc1.weight)
print(model.fc1.bias)

Parameter containing:
tensor([[ 0.2983, -0.1232,  0.1068, -0.2998,  0.0379, -0.0979,  0.0318, -0.2529,
         -0.0285,  0.0936],
        [ 0.1883,  0.1639,  0.1017, -0.2306, -0.2901, -0.0996,  0.1424,  0.1477,
         -0.2494,  0.2897],
        [-0.0549,  0.0656,  0.1244, -0.2833,  0.1625,  0.0140,  0.0330,  0.1947,
          0.0240, -0.2193],
        [ 0.2241, -0.0385, -0.1412, -0.2481,  0.2682,  0.2056, -0.1867,  0.0024,
         -0.2938, -0.1592],
        [ 0.2007, -0.2040,  0.0371, -0.2019, -0.2085, -0.1062, -0.0727,  0.2017,
          0.1444,  0.1895]], requires_grad=True)
Parameter containing:
tensor([ 0.2402, -0.0765,  0.1730,  0.2358,  0.0330], requires_grad=True)


In [5]:
model.fc1.bias.data.fill_(0)

tensor([0., 0., 0., 0., 0.])

In [6]:
model.fc1.weight.data.normal_(std=1)

tensor([[ 0.4068, -0.6836,  0.8289,  0.5547, -0.4418, -1.5611, -1.9122, -0.3331,
         -0.9655, -0.0863],
        [ 0.2698,  2.0728,  0.3332, -0.7452, -0.9937,  0.3220, -0.6669, -0.7752,
         -0.4645, -2.9333],
        [-0.0093, -0.0370,  0.3607,  0.4764,  0.0739, -0.5168, -0.5190, -1.0155,
          0.7964,  0.2871],
        [-0.3969,  0.1779,  0.6664, -0.0563,  0.4282, -0.2499, -0.2138, -0.8132,
          0.7096,  1.4582],
        [ 0.2951,  1.3115, -0.8419,  1.2112, -0.6855,  0.7936,  2.2440, -0.7277,
          1.9618,  0.3273]])

In [7]:
df= pd.read_csv("load.csv")
df

Timestep            date   load
0          0   6/1/2020 0:00  0.123
1        900   6/1/2020 0:15  0.070
2       1800   6/1/2020 0:30  0.121
3       2700   6/1/2020 0:45  0.926
4       3600   6/1/2020 1:00  0.713
..       ...             ...    ...
91     81900  6/1/2020 22:45  0.993
92     82800  6/1/2020 23:00  0.761
93     83700  6/1/2020 23:15  0.590
94     84600  6/1/2020 23:30  0.579
95     85500  6/1/2020 23:45  0.131

[96 rows x 3 columns]

In [8]:
input_df= pd.read_csv("sample_data_1.csv")
input_df

TIME   V_BUS1_A   V_BUS1_B   V_BUS1_C   V_BUS2_A   V_BUS2_B   V_BUS2_C  \
0    0.1  12.431100  12.421388  12.193497  11.744752  12.001407  11.669493   
1    0.2  12.255631  12.460345  12.405883  12.275021  12.251495  11.795322   
2    0.3  11.692576  11.610360  12.202112  12.452020  12.019292  11.637779   
3    0.4  11.825617  12.402174  11.989781  12.365791  12.351166  12.497587   
4    0.5  11.620118  12.206632  12.065417  12.176510  11.758156  11.989235   
..   ...        ...        ...        ...        ...        ...        ...   
94   9.5  12.224328  12.128030  11.946022  12.241880  11.628409  12.492607   
95   9.6  12.365140  11.754394  12.259339  12.053893  11.726074  11.847809   
96   9.7  11.989402  11.942026  12.288952  12.322753  11.508977  11.503765   
97   9.8  12.102556  12.122280  12.384296  11.744335  11.977611  11.503592   
98   9.9  11.727083  11.613022  11.800369  11.731934  11.934723  12.029585   

    BESS_1_SOC  BESS_1_P  BESS_1_Q  ...  PV1_Q  BESS_2_SOC  BESS_2_P  \
0           48       312       137  ...    442          20       186   
1           63       199      -432  ...    402          67       236   
2           54       -68       138  ...    284          20      -467   
3           33       434      -267  ...    494          28       195   
4           80       451      -360  ...    453          71       154   
..         ...       ...       ...  ...    ...         ...       ...   
94          48        97      -318  ...    223          90       -25   
95          27      -311      -227  ...     33          88       232   
96          78       244      -470  ...    442          42      -364   
97          38      -235       -49  ...    488          57       123   
98          65      -134       -88  ...     51          41       404   

    BESS_2_Q  PV2_P  PV2_Q  BUS1_load_P  BUS1_load_Q  BUS2_load_P  BUS2_load_Q  
0        331    172    336          439          152          318          113  
1       -362     77    127          561           93          359          188  
2         12    324    434          567          133          147          158  
3        460     66    234          295           77          397          148  
4        474    297    471          204          123          381           90  
..       ...    ...    ...          ...          ...          ...          ...  
94       110    165     67          272          186          320          195  
95       380     74    242          299          140          142          169  
96       294    389    167          441          179          193          145  
97       476    257    465          452           82          311           57  
98       317    399    309          412          123          330           68  

[99 rows x 21 columns]

In [9]:
col = 'BESS_1_SOC'
soc_up_lim = 80
normalization_factor = 95
df_filter = input_df.where(input_df.loc[:, col] > soc_up_lim).dropna()
df_filter

TIME   V_BUS1_A   V_BUS1_B   V_BUS1_C   V_BUS2_A   V_BUS2_B   V_BUS2_C  \
7    0.8  11.857544  11.756284  11.809737  12.392437  12.073684  11.716582   
8    0.9  12.088665  11.777760  11.799340  12.216636  11.832937  11.990729   
16   1.7  12.324257  12.394161  12.201959  12.380469  12.002473  11.615185   
19   2.0  11.899185  12.245784  11.505784  12.158011  12.102115  11.937177   
26   2.7  12.391890  11.540887  11.966646  11.738761  12.104192  12.242821   
35   3.6  12.122373  12.344178  12.143567  11.680141  12.378140  12.051469   
36   3.7  12.243011  11.916786  12.380346  12.028635  11.963532  11.603412   
39   4.0  11.954848  11.825071  11.816454  12.135539  12.226559  12.471716   
52   5.3  12.022255  12.470333  12.186752  11.682627  11.991593  11.997963   
53   5.4  12.004821  11.720371  12.472741  11.771291  11.723174  12.153828   
63   6.4  12.050970  12.225667  12.324753  11.917172  12.255941  11.936616   
65   6.6  12.158511  12.075158  12.044665  11.706435  12.377493  12.344490   
78   7.9  12.109282  11.637231  11.833487  11.506655  12.033749  12.059343   
79   8.0  11.843133  12.393802  12.257640  12.075156  11.683293  12.300095   
86   8.7  11.781945  12.152947  12.449561  11.587375  11.791673  11.856879   
91   9.2  11.544319  12.247955  12.022160  12.451451  12.017196  12.478284   

    BESS_1_SOC  BESS_1_P  BESS_1_Q  ...  PV1_Q  BESS_2_SOC  BESS_2_P  \
7         94.0     235.0    -467.0  ...   80.0        77.0     171.0   
8         93.0    -136.0    -278.0  ...  208.0        89.0     497.0   
16        94.0      44.0     197.0  ...  206.0        38.0    -112.0   
19        95.0     287.0    -394.0  ...  232.0        56.0     214.0   
26        88.0    -411.0    -379.0  ...  448.0        77.0     111.0   
35        88.0    -434.0    -126.0  ...  306.0        46.0     -84.0   
36        81.0     241.0    -335.0  ...  454.0        61.0    -426.0   
39        92.0    -210.0    -194.0  ...   20.0        70.0     -56.0   
52        89.0    -262.0     327.0  ...  167.0        38.0    -299.0   
53        82.0     154.0    -224.0  ...  462.0        55.0    -269.0   
63        93.0    -353.0    -390.0  ...  197.0        59.0     452.0   
65        90.0    -137.0     239.0  ...  294.0        34.0      41.0   
78        93.0     110.0     -38.0  ...  358.0        36.0     291.0   
79        94.0     154.0     342.0  ...  165.0        47.0    -113.0   
86        96.0     283.0    -196.0  ...  344.0        85.0      64.0   
91        91.0      -4.0    -308.0  ...  178.0        55.0    -128.0   

    BESS_2_Q  PV2_P  PV2_Q  BUS1_load_P  BUS1_load_Q  BUS2_load_P  BUS2_load_Q  
7      266.0  348.0  106.0        410.0        134.0        455.0         62.0  
8      459.0  333.0  113.0        549.0         89.0        525.0         78.0  
16     119.0  235.0  324.0        326.0        147.0        200.0        171.0  
19     334.0  240.0  105.0        469.0        187.0        112.0         93.0  
26     414.0   39.0  395.0        519.0         57.0        211.0        142.0  
35    -234.0  359.0  152.0         52.0         90.0         99.0        128.0  
36      43.0   76.0    6.0        407.0         75.0        321.0        188.0  
39     416.0  355.0  282.0        182.0        116.0        212.0         54.0  
52    -418.0  376.0  260.0        279.0        185.0        356.0        132.0  
53     162.0  165.0  385.0        309.0        123.0        193.0        156.0  
63     -26.0  378.0  208.0        375.0        125.0        355.0        141.0  
65     439.0  410.0  154.0        350.0         61.0        168.0         73.0  
78     113.0   36.0  301.0        129.0         73.0        577.0        173.0  
79     341.0  391.0  459.0        312.0         87.0        286.0        132.0  
86     116.0  166.0  499.0        203.0        176.0        559.0         61.0  
91    -205.0  301.0   11.0        598.0         86.0        417.0        163.0  

[16 rows x 21 columns]

In [10]:
df_filter['reward'] = (df_filter.loc[:, col]) / normalization_factor
df_filter

TIME   V_BUS1_A   V_BUS1_B   V_BUS1_C   V_BUS2_A   V_BUS2_B   V_BUS2_C  \
7    0.8  11.857544  11.756284  11.809737  12.392437  12.073684  11.716582   
8    0.9  12.088665  11.777760  11.799340  12.216636  11.832937  11.990729   
16   1.7  12.324257  12.394161  12.201959  12.380469  12.002473  11.615185   
19   2.0  11.899185  12.245784  11.505784  12.158011  12.102115  11.937177   
26   2.7  12.391890  11.540887  11.966646  11.738761  12.104192  12.242821   
35   3.6  12.122373  12.344178  12.143567  11.680141  12.378140  12.051469   
36   3.7  12.243011  11.916786  12.380346  12.028635  11.963532  11.603412   
39   4.0  11.954848  11.825071  11.816454  12.135539  12.226559  12.471716   
52   5.3  12.022255  12.470333  12.186752  11.682627  11.991593  11.997963   
53   5.4  12.004821  11.720371  12.472741  11.771291  11.723174  12.153828   
63   6.4  12.050970  12.225667  12.324753  11.917172  12.255941  11.936616   
65   6.6  12.158511  12.075158  12.044665  11.706435  12.377493  12.344490   
78   7.9  12.109282  11.637231  11.833487  11.506655  12.033749  12.059343   
79   8.0  11.843133  12.393802  12.257640  12.075156  11.683293  12.300095   
86   8.7  11.781945  12.152947  12.449561  11.587375  11.791673  11.856879   
91   9.2  11.544319  12.247955  12.022160  12.451451  12.017196  12.478284   

    BESS_1_SOC  BESS_1_P  BESS_1_Q  ...  BESS_2_SOC  BESS_2_P  BESS_2_Q  \
7         94.0     235.0    -467.0  ...        77.0     171.0     266.0   
8         93.0    -136.0    -278.0  ...        89.0     497.0     459.0   
16        94.0      44.0     197.0  ...        38.0    -112.0     119.0   
19        95.0     287.0    -394.0  ...        56.0     214.0     334.0   
26        88.0    -411.0    -379.0  ...        77.0     111.0     414.0   
35        88.0    -434.0    -126.0  ...        46.0     -84.0    -234.0   
36        81.0     241.0    -335.0  ...        61.0    -426.0      43.0   
39        92.0    -210.0    -194.0  ...        70.0     -56.0     416.0   
52        89.0    -262.0     327.0  ...        38.0    -299.0    -418.0   
53        82.0     154.0    -224.0  ...        55.0    -269.0     162.0   
63        93.0    -353.0    -390.0  ...        59.0     452.0     -26.0   
65        90.0    -137.0     239.0  ...        34.0      41.0     439.0   
78        93.0     110.0     -38.0  ...        36.0     291.0     113.0   
79        94.0     154.0     342.0  ...        47.0    -113.0     341.0   
86        96.0     283.0    -196.0  ...        85.0      64.0     116.0   
91        91.0      -4.0    -308.0  ...        55.0    -128.0    -205.0   

    PV2_P  PV2_Q  BUS1_load_P  BUS1_load_Q  BUS2_load_P  BUS2_load_Q    reward  
7   348.0  106.0        410.0        134.0        455.0         62.0  0.989474  
8   333.0  113.0        549.0         89.0        525.0         78.0  0.978947  
16  235.0  324.0        326.0        147.0        200.0        171.0  0.989474  
19  240.0  105.0        469.0        187.0        112.0         93.0  1.000000  
26   39.0  395.0        519.0         57.0        211.0        142.0  0.926316  
35  359.0  152.0         52.0         90.0         99.0        128.0  0.926316  
36   76.0    6.0        407.0         75.0        321.0        188.0  0.852632  
39  355.0  282.0        182.0        116.0        212.0         54.0  0.968421  
52  376.0  260.0        279.0        185.0        356.0        132.0  0.936842  
53  165.0  385.0        309.0        123.0        193.0        156.0  0.863158  
63  378.0  208.0        375.0        125.0        355.0        141.0  0.978947  
65  410.0  154.0        350.0         61.0        168.0         73.0  0.947368  
78   36.0  301.0        129.0         73.0        577.0        173.0  0.978947  
79  391.0  459.0        312.0         87.0        286.0        132.0  0.989474  
86  166.0  499.0        203.0        176.0        559.0         61.0  1.010526  
91  301.0   11.0        598.0         86.0        417.0        163.0  0.957895  

[16 rows x 22 columns]

In [11]:
reward = df_filter.reward.sum()
df_filter
print(reward)
(reward/input_df.shape[0])*10

15.294736842105262


1.544922913343966

In [12]:
def dual_resource(input_df,bus_load, BESS_kw_cap, time):
    # if between 6AM and 6PM or PV kw >10 , then BESS should not discharge unless load > PV size.
    # sign convention: kW<0 -> power drawn from the grid, batteries charged.
    #                  kW>0 -> power into the grid, batteries discharged.

    # we want to count number of occurrence where PV is available AND load < PV_output  AND P_BESS > 0
    # In this case we need to punish the agent, the reward should be calculated as follows:
    # ( number of occurrence in each 15 minutes(real time) -> 60 seconds(simulation)/number of samples )*100

    # This is to address the condition load < PV_output  AND P_BESS > 0
    df_filter = input_df.where(input_df.load < input_df.PV1_P).dropna()
    df_filter = input_df.where(input_df.BESS_1_P < 0).dropna()
    max_discharge = -1 * df_filter.BESS_1_P.min()
    # This will make the reward between 0 and 1
    df_filter['reward'] = -1 * (df_filter.BESS_1_P / BESS_kw_cap)
    # reward need to get updated
    return 1

In [13]:
dual_resource(input_df, 'BUS1_load_P' ,500,9)

AttributeError: 'DataFrame' object has no attribute 'load'